# version: "3.8"
# services:
#   web:
#     build: .
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db
#     environment:
#       - DATABASE_URL=postgresql://postgres:password@db:5432/grocery_db
#     volumes:
#       - .:/app

#   db:
#     image: postgres:15
#     environment:
#       POSTGRES_DB: grocery_db
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: password
#     ports:
#       - "5433:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
# volumes:
#   postgres_data:

version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://grocery_user:grocery_pass@db:5432/grocery_db
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=grocery_db
      - POSTGRES_USER=grocery_user
      - POSTGRES_PASSWORD=grocery_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://grocery_user:grocery_pass@db:5432/grocery_db
    # command: python -m app.workers.background_tasks

volumes:
  postgres_data:
    name: grocery_volume
